import CoreSpotlight
import Foundation
import os
import PinfoldCore

// MARK: - SpotlightID

/// The identifier scheme for Core Spotlight items. Two shapes:
/// - **Entry item:** the bare folder name (`"<folderName>"`).
/// - **Placemark item:** `"<folderName>/<stableKey>"`.
///
/// ## Why splitting on the FIRST "/" is unambiguous
///
/// A placemark's `stableKey` can be `"id:<sourceID>"` where `sourceID` is an arbitrary
/// author-supplied string that may itself contain "/" (e.g. `"id:a/b/c"`). The folder name,
/// by contrast, is **always a UUID string** (generated by `ImportService.prepare`), which
/// never contains "/". So the first "/" in a composite id always separates the folder name
/// from the (possibly slash-bearing) placemark key — split there and the key survives intact.
enum SpotlightID {
    /// The Spotlight unique identifier for an entry item.
    static func entry(folderName: String) -> String {
        folderName
    }

    /// The Spotlight unique identifier for a placemark item.
    static func placemark(folderName: String, placemarkKey: String) -> String {
        "\(folderName)/\(placemarkKey)"
    }

    /// Parses a Spotlight identifier back into its components.
    ///
    /// - Returns: `(folderName, placemarkKey)` where `placemarkKey` is `nil` for an entry item,
    ///   or `nil` when `raw` is malformed. Malformed means: empty, an empty folder name (a
    ///   leading "/"), or an empty placemark key (a trailing "/"). The folder-name invariant
    ///   (a non-empty UUID string with no "/") makes the first-"/" split unambiguous.
    static func parse(_ raw: String) -> (folderName: String, placemarkKey: String?)? {
        guard !raw.isEmpty else { return nil }
        guard let slash = raw.firstIndex(of: "/") else {
            // No "/" → an entry item (bare folder name).
            return (raw, nil)
        }
        let folderName = String(raw[..<slash])
        let key = String(raw[raw.index(after: slash)...])
        guard !folderName.isEmpty, !key.isEmpty else { return nil }
        return (folderName, key)
    }
}

// MARK: - SpotlightIndexer

/// Builds and maintains the Core Spotlight index of catalogue entries and their placemarks so
/// the app's offline content is reachable from system search.
///
/// The **pure builder** (`items(for:indexEntries:)` + `SpotlightID`) is the unit-tested
/// surface. The thin wrappers (`index`/`deindex`) are fire-and-forget over
/// the live `CSSearchableIndex.default()`: they detach in `nonisolated` free functions (so the
/// `Task.detached` closures don't get compiled into a `@MainActor` caller's SIL) and log any
/// failure rather than surfacing it — a missing search index is non-fatal and self-heals on the
/// next import/materialization pass.
enum SpotlightIndexer {
    /// Domain identifier for entry items (one per catalogue file).
    static let entryDomain = "entries"
    /// Domain identifier for placemark items (one per named placemark).
    static let placemarkDomain = "placemarks"

    fileprivate static let logger = Logger(
        subsystem: Bundle.main.bundleIdentifier ?? "Pinfold",
        category: "spotlight"
    )

    // MARK: - Pure builder

    /// Builds the searchable items for one entry: one item per **named** placemark (nameless
    /// placemarks are skipped — there's nothing to match on) plus one item for the entry itself.
    ///
    /// - Placemark items: `domainIdentifier == "placemarks"`, `title` = placemark name,
    ///   `contentDescription` = the entry's display name (so a hit reads "Colosseum — Rome
    ///   Trip"), `latitude`/`longitude` set when the placemark has a coordinate, and
    ///   `supportsNavigation` flagged so Spotlight can offer directions.
    /// - Entry item: `domainIdentifier == "entries"`, `title` = display name,
    ///   `contentDescription` = a simple "<pointCount> places" string.
    static func items(for entry: CatalogEntry, indexEntries: [PlacemarkIndex.Entry]) -> [CSSearchableItem] {
        var items: [CSSearchableItem] = []

        for placemark in indexEntries where !placemark.name.isEmpty {
            let attributes = CSSearchableItemAttributeSet(contentType: .content)
            attributes.title = placemark.name
            attributes.contentDescription = entry.displayName
            if let lat = placemark.lat, let lon = placemark.lon {
                attributes.latitude = NSNumber(value: lat)
                attributes.longitude = NSNumber(value: lon)
                attributes.supportsNavigation = 1
            }
            let item = CSSearchableItem(
                uniqueIdentifier: SpotlightID.placemark(
                    folderName: entry.storageFolderName,
                    placemarkKey: placemark.key
                ),
                domainIdentifier: placemarkDomain,
                attributeSet: attributes
            )
            items.append(item)
        }

        let entryAttributes = CSSearchableItemAttributeSet(contentType: .content)
        entryAttributes.title = entry.displayName
        entryAttributes.contentDescription = "\(entry.pointCount) places"
        let entryItem = CSSearchableItem(
            uniqueIdentifier: SpotlightID.entry(folderName: entry.storageFolderName),
            domainIdentifier: entryDomain,
            attributeSet: entryAttributes
        )
        items.append(entryItem)

        return items
    }

    // MARK: - Live-index wrappers (fire-and-forget)

    /// Indexes (or re-indexes) every item for `entry`. Fire-and-forget.
    static func index(entry: CatalogEntry, indexEntries: [PlacemarkIndex.Entry]) {
        let items = items(for: entry, indexEntries: indexEntries)
        spotlightIndex(items)
    }

    /// Removes every Spotlight item belonging to `folderName`: its entry item plus all of its
    /// placemark items. The placemark ids are reconstructed from `indexEntries` (the same
    /// `placemarks-index.json` rows used to index them), so the full id list is deleted in one
    /// call. Pass `indexEntries: []` when the index can't be read (e.g. the folder is already
    /// gone) — at minimum the entry item is removed. Fire-and-forget.
    static func deindex(folderName: String, indexEntries: [PlacemarkIndex.Entry]) {
        var ids = [SpotlightID.entry(folderName: folderName)]
        for placemark in indexEntries where !placemark.name.isEmpty {
            ids.append(SpotlightID.placemark(folderName: folderName, placemarkKey: placemark.key))
        }
        spotlightDeindex(identifiers: ids)
    }
}

// MARK: - Off-main detach (free functions)

/// Submits `items` to the default Core Spotlight index off-main, logging any failure. A
/// `nonisolated` free function so the `Task.detached` closure is compiled here rather than
/// inside a `@MainActor` caller's SIL (mirrors `FavoritesView`'s pattern).
private func spotlightIndex(_ items: [CSSearchableItem]) {
    guard !items.isEmpty else { return }
    // `CSSearchableItem` isn't `Sendable`, but these items are freshly built here and never
    // touched again after this call — ownership transfers wholly into the detached task, so the
    // capture is race-free. `nonisolated(unsafe)` asserts that to the compiler.
    nonisolated(unsafe) let items = items
    Task.detached(priority: .utility) {
        do {
            try await CSSearchableIndex.default().indexSearchableItems(items)
        } catch {
            SpotlightIndexer.logger.error(
                "Failed to index \(items.count) Spotlight item(s): \(error.localizedDescription, privacy: .public)"
            )
        }
    }
}

/// Deletes the given Spotlight item identifiers off-main, logging any failure. A `nonisolated`
/// free function so the `Task.detached` closure stays out of any `@MainActor` caller's SIL.
private func spotlightDeindex(identifiers: [String]) {
    guard !identifiers.isEmpty else { return }
    Task.detached(priority: .utility) {
        do {
            try await CSSearchableIndex.default()
                .deleteSearchableItems(withIdentifiers: identifiers)
        } catch {
            SpotlightIndexer.logger.error(
                """
                Failed to deindex \(identifiers.count) Spotlight item(s): \
                \(error.localizedDescription, privacy: .public)
                """
            )
        }
    }
}
